---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kolya-bot
  namespace: kolya-bot
spec:
  selector:
    matchLabels:
      app: kolya-bot
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kolya-bot
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
      containers:
      - name: kolya-bot
        image: north21/kolya_bot
        volumeMounts:
        - name: kolya-bot-storage
          mountPath: /tmp
        startupProbe:
          exec:
            command: ["sh", "-c", "pgrep bot || exit 1"]
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 30
        livenessProbe:
          exec:
            command: ["sh", "-c", "pgrep bot || exit 1"]
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          exec:
            command: ["sh", "-c", "pgrep bot || exit 1"]
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
          - name: TELEGRAM_APITOKEN
            valueFrom:
              secretKeyRef:
                name: kolya-bot-telegram-api-token
                key: token
          - name: weatherapi_key
            valueFrom:
              secretKeyRef:
                name: weatherapi-key
                key: key
          - name: anecdotica_pid
            valueFrom:
              secretKeyRef:
                name: anecdotica
                key: pid
          - name: anecdotica_key
            valueFrom:
              secretKeyRef:
                name: anecdotica
                key: key
          - name: fusionbrain_key
            valueFrom:
              secretKeyRef:
                name: fusionbrain
                key: key
          - name: fusionbrain_secret
            valueFrom:
              secretKeyRef:
                name: fusionbrain
                key: secret
          - name: CHAT_URL
            value: "ddg-chat.kolya-bot.svc.cluster.local:8787"
          - name: MODEL
            value: "gpt-4o-mini"
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
      - name: ddg-chat
        image: leafmoes/ddg-chat:latest
        ports:
        - containerPort: 8787
        livenessProbe:
          httpGet:
            path: /ping
            port: 8787
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ping
            port: 8787
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
      volumes:
      - name: kolya-bot-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ddg-chat
spec:
  type: ClusterIP
  ports:
    - port: 8787
      targetPort: 8787
  selector:
    app: kolya-bot

