---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kolya-bot
  namespace: kolya-bot
spec:
  selector:
    matchLabels:
      app: kolya-bot
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kolya-bot
    spec:
      containers:
      - name: kolya-bot
        image: north21/kolya_bot:202410171028 # change for automatic deployment!
        startupProbe:
          exec:
            command: ["sh", "-c", "pgrep bot || exit 1"]
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 30
        livenessProbe:
          exec:
            command: ["sh", "-c", "pgrep bot || exit 1"]
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          exec:
            command: ["sh", "-c", "pgrep bot || exit 1"]
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
          - name: TELEGRAM_APITOKEN
            valueFrom:
              secretKeyRef:
                name: kolya-bot-telegram-api-token
                key: token
          - name: weatherapi_key
            valueFrom:
              secretKeyRef:
                name: weatherapi-key
                key: key
          - name: anecdotica_pid
            valueFrom:
              secretKeyRef:
                name: anecdotica
                key: pid
          - name: anecdotica_key
            valueFrom:
              secretKeyRef:
                name: anecdotica
                key: key
        securityContext:
          runAsNonRoot: true
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
