version: '3'

services:
  bot:
    image: north21/kolya_bot:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - .env

