
name: Build, Test, and Push Docker Image
on:
  push:
    branches:
      - main
    paths:
      - '*.go'
      - 'Dockerfile'

env:
  IMAGE: north21/kolya_bot
  
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@6e04d228eb30da1757ee4e1dd75a0ec73a653e06 #v3.1.1
        with:
          cosign-release: 'v2.1.1'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t "${IMAGE}:latest" .
          docker tag "${IMAGE}:latest" "${IMAGE}:$(date +%Y%m%d%H%M)"

      - name: Test Docker image
        run: docker run --rm "${IMAGE}:latest" ls -la | grep bot

      # - name: Run Go tests
      #   run: docker run --rm "${IMAGE}:latest" go test -vvv
      
      - name: Push Docker image
        run: |
          docker push -a "${IMAGE}"

