name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - '**'  # Срабатывает на пуши в любые ветки
    paths:
      - '*.go'
      - 'Dockerfile'

env:
  IMAGE: north21/kolya_bot

jobs:
#   test:
#     name: Run Tests
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Go
#         uses: actions/setup-go@v2
#         with:
#           go-version: 1.20.3

#       - name: Run Tests
#         run: go test -v

  build:
    # needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.1.1
        with:
          cosign-release: 'v2.1.1'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        id: build
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M)
          echo "TIMESTAMP=${TIMESTAMP}" >> $GITHUB_ENV
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            docker build -t "${IMAGE}:latest" .
          else
            docker build -t "${IMAGE}:${TIMESTAMP}" .
          fi

      - name: Test Docker image
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            docker run --rm "${IMAGE}:latest" ls -la | grep bot
          else
            docker run --rm "${IMAGE}:${{ env.TIMESTAMP }}" ls -la | grep bot
          fi

      - name: Push Docker image
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            docker push "${IMAGE}:latest"
          else
            docker push "${IMAGE}:${{ env.TIMESTAMP }}"
          fi

